name: Document Review Check

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight

jobs:
  check-documents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install yaml-front-matter axios glob
      - name: Check documents
        run: node .github/scripts/check_documents.js
        env:
          GLITCH_WEBHOOK_URL: ${{ secrets.GLITCH_WEBHOOK_URL }}
