name: Update Document and Create PR

on:
  workflow_dispatch:
    inputs:
      path:
        required: true
        description: 'File path of the document to update'
      title:
        required: true
        description: 'Title of the document'

jobs:
  update-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Update Document
        run: |
          echo "Attempting to update document at ${{ github.workspace }}/${{ github.event.inputs.path }}"
          sed -i 's/old_text/new_text/g' ${{ github.workspace }}/${{ github.event.inputs.path }}  # Adjusted path
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ github.workspace }}/${{ github.event.inputs.path }}
          git commit -m "Update review date for ${{ github.event.inputs.title }}"
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "update-${{ github.run_id }}"
          commit-message: "Update review date for ${{ github.event.inputs.title }}"
          title: "Review Update: ${{ github.event.inputs.title }}"
          body: "This PR updates the document as required."
          delete-branch: true
