name: Update Document and Create PR

on:
  workflow_dispatch:
    inputs:
      path:
        required: true
        description: 'Relative file path of the document to update from the repository root'
      title:
        required: true
        description: 'Title of the document'


jobs:
  update-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.YOUR_PAT_SECRET_NAME }} # Use the PAT instead of the default GITHUB_TOKEN

      - name: Display file content before changes
        run: cat .docs/${{ github.event.inputs.path }}
    
      - name: Update Document
        run: |
          sed -i "s/last_reviewed_on:.*/last_reviewed_on: 2024-05-02/" .docs/${{ github.event.inputs.path }}

      - name: Display file content after changes
        run: cat .docs/${{ github.event.inputs.path }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .docs/${{ github.event.inputs.path }}
          git commit -m "Updated review date for ${{ github.event.inputs.title }}" || echo "No changes to commit."

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.YOUR_PAT_SECRET_NAME }} # Use the PAT here too
          branch: "update-${{ github.run_id }}"
          commit-message: "Update review date for ${{ github.event.inputs.title }}"
          title: "Review Update: ${{ github.event.inputs.title }}"
          body: "This PR updates the last reviewed date for the document."
          delete-branch: true
          draft: false

