name: Update Document and Create PR

on:
  workflow_dispatch:
    inputs:
      path:
        required: true
        description: 'The file path of the document to update'
      title:
        required: true
        description: 'The title of the document to be used in commit and PR title'

jobs:
  update-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Update Document
        run: |
          echo "Document updates would be scripted here"
          # Example: Update the document's review date in its metadata
          sed -i 's/old_date/new_date/g' ${{ github.event.inputs.path }}
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ github.event.inputs.path }}
          git commit -m "Update review date for ${{ github.event.inputs.title }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "review-update-${{ github.run_id }}"
          delete-branch: true
          title: "Review Update: ${{ github.event.inputs.title }}"
          body: "Automated PR to update review date for ${{ github.event.inputs.title }}"
          base: 'main'  # Your default branch
